# Generated by Django 4.2.11 on 2024-06-19 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_studentmark_delete_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('book_name', models.CharField(max_length=100)),
                ('final_score', models.IntegerField()),
                ('incorrect_answers_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('correct_version', models.TextField()),
                ('student_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_review', to='api.studentreview')),
            ],
        ),
    ]
