# Generated by Django 4.2.11 on 2024-06-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_studentreview_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentMark',
        ),
    ]
