# Generated by Django 4.2.11 on 2024-07-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_questiondetail_correct_version_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiondetail',
            old_name='correct_answer',
            new_name='correct_version',
        ),
        migrations.RemoveField(
            model_name='questiondetail',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='questiondetail',
            name='section',
        ),
        migrations.RemoveField(
            model_name='studentreview',
            name='correct_answers',
        ),
        migrations.RemoveField(
            model_name='studentreview',
            name='correct_answers_total_marks',
        ),
        migrations.RemoveField(
            model_name='studentreview',
            name='incorrect_answers_total_marks',
        ),
        migrations.RemoveField(
            model_name='studentreview',
            name='total_marks',
        ),
        migrations.RemoveField(
            model_name='studentreview',
            name='total_questions',
        ),
        migrations.AddField(
            model_name='questiondetail',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='questiondetail',
            name='question_number',
            field=models.IntegerField(null=True),
        ),
    ]
