# Generated by Django 4.2.11 on 2024-08-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_correct_version_questiondetail_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondetail',
            name='reason',
            field=models.TextField(null=True),
        ),
    ]
